In [3]:
import numpy as np
a=np.array([1,6,3,4,6,5])
x=np.where(a==6)
print(x)

(array([1, 4], dtype=int64),)


In [5]:
x=np.where(a==3)
print(x)

(array([2], dtype=int64),)


In [6]:
b=np.array([0,1,2,2,7,8,9])
y=np.searchsorted(b,3,side='left')
print(y)

4


In [10]:
y=np.searchsorted(b,8,side='right')
print(y)

6


In [11]:
y=np.searchsorted(b,8,side='left')
print(y)

5


In [15]:
c=np.array([9,5,2,7,6,4])
print(np.sort(c))


[2 4 5 6 7 9]


In [14]:
d=np.array([[7,4,9],[9,1,4]])
print(np.sort(d))

[[4 7 9]
 [1 4 9]]


In [16]:
x=np.array([31,78,69,88])
y=[False,True,False,True]
new=x[y]
print(y)
print(new)

[False, True, False, True]
[78 88]


In [20]:
x=np.array([31,78,69,88])
filter=x<70
new=x[filter]
print(filter)
print(new)

[ True False  True False]
[31 69]
