In [9]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
sli=arr[2:6]
print(sli)

[3 4 5 6]


In [11]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
sli=arr[2:8:2]
print(sli)

[3 5 7]


In [12]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
sli=arr[::2]
print(sli)

[1 3 5 7 9]


In [13]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
sli=arr[::-1]
print(sli)

[9 8 7 6 5 4 3 2 1]


In [15]:
import numpy as np
b=np.array([[5,10,15],[20,25,30],[35,40,45]])
new=b[0:2,1:3]
print(new)


[[10 15]
 [25 30]]


In [27]:
col=b[:,0]
row=b[2,]
print(col)
print(row)

[ 5 20 35]
[35 40 45]


In [26]:
print(b[0,0])
print(b[1,2])

5
30


In [24]:
c=np.array([3,6,9,12,15,18,21])
print(c[1])

6
21


In [25]:
print(c[-2])

18


In [28]:
print(c[1:5])

[ 6  9 12 15]


In [31]:
print(c[c>12])

[15 18 21]


In [35]:
x=np.array([[10,20,30],[40,50,60]])
y=np.array([[5,15,25],[35,45,55]])
res=np.hstack((x,y))
print(res)

[[10 20 30  5 15 25]
 [40 50 60 35 45 55]]


In [37]:
res=np.vstack((x,y))
print(res)

[[10 20 30]
 [40 50 60]
 [ 5 15 25]
 [35 45 55]]


In [38]:
res=np.dstack((x,y))
print(res)

[[[10  5]
  [20 15]
  [30 25]]

 [[40 35]
  [50 45]
  [60 55]]]


In [46]:
z=np.array_split(arr,3)
print(z)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [49]:
z=np.array_split(arr,2)
print(z)

[array([1, 2, 3, 4, 5]), array([6, 7, 8, 9])]
